### ISSUE TITLE
docker bootstrap faild when i add web.china.template.yml

### ISSUE THREAD

**Issue by paomian** [discourse/discourse_docker#113]
i am a chinese, it is so slow to bundle install from rubygems.org, so i add web.china.template.yml,but i get the error
```
2014-11-24 09:53:34 UTC LOG:  received fast shutdown request
2014-11-24 09:53:34 UTC LOG:  aborting any active transactions
2014-11-24 09:53:34 UTC LOG:  autovacuum launcher shutting down
2014-11-24 09:53:34 UTC LOG:  shutting down
[180 | signal handler] (1416822814) Received SIGTERM scheduling shutdown...
[180] 24 Nov 09:53:34.579 # User requested shutdown...
[180] 24 Nov 09:53:34.579 * Saving the final RDB snapshot before exiting.
[180] 24 Nov 09:53:40.486 * DB saved on disk
[180] 24 Nov 09:53:40.486 # Redis is now ready to exit, bye bye...
I, [2014-11-24T09:53:44.584528 #40]  INFO -- : HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/9.3/bin/postmaster -D /etc/postgresql/9.3/main pid:67 did not terminate cleanly, forcing termination!
/pups/lib/pups/config.rb:93:in `block (2 levels) in run_commands': Invalid run command cmd (SyntaxError)
	from /pups/lib/pups/config.rb:87:in `each'
	from /pups/lib/pups/config.rb:87:in `block in run_commands'
	from /pups/lib/pups/config.rb:86:in `each'
	from /pups/lib/pups/config.rb:86:in `run_commands'
	from /pups/lib/pups/config.rb:71:in `run'
	from /pups/lib/pups/cli.rb:31:in `run'
	from /pups/bin/pups:8:in `<main>'
3aa707b645a27211c38f452718a78d275ac572c018304154c086071ec1be0d15
FAILED TO BOOTSTRAP
```

**Comment by SamSaffron** [comment]
Unlclear if this is still an issue, @fantasticfears closing this, let me know if it needs opening
