### ISSUE TITLE
Bootstrap Failure PSQL: Could not connect

### ISSUE THREAD

**Issue by domschiener** [discourse/discourse_docker#277]
```
I, [2016-08-09T08:57:58.888739 #15]  INFO -- : Upgrading PostgreSQL to from version to 9.5

I, [2016-08-09T08:57:58.889081 #15]  INFO -- : > rm /root/upgrade_postgres
I, [2016-08-09T08:57:58.890668 #15]  INFO -- : 
I, [2016-08-09T08:57:58.891057 #15]  INFO -- : Replacing data_directory = '/var/lib/postgresql/9.5/main' with data_directory = '/shared/postgres_data' in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.891767 #15]  INFO -- : Replacing (?-mix:#?listen_addresses *=.*) with listen_addresses = '*' in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.892463 #15]  INFO -- : Replacing (?-mix:#?synchronous_commit *=.*) with synchronous_commit = $db_synchronous_commit in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.892933 #15]  INFO -- : Replacing (?-mix:#?shared_buffers *=.*) with shared_buffers = $db_shared_buffers in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.893406 #15]  INFO -- : Replacing (?-mix:#?work_mem *=.*) with work_mem = $db_work_mem in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.893949 #15]  INFO -- : Replacing (?-mix:#?default_text_search_config *=.*) with default_text_search_config = '$db_default_text_search_config' in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.894410 #15]  INFO -- : > install -d -m 0755 -o postgres -g postgres /shared/postgres_backup
I, [2016-08-09T08:57:58.896496 #15]  INFO -- : 
I, [2016-08-09T08:57:58.896946 #15]  INFO -- : Replacing (?-mix:#?max_wal_senders *=.*) with max_wal_senders = $db_max_wal_senders in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.897424 #15]  INFO -- : Replacing (?-mix:#?wal_level *=.*) with wal_level = $db_wal_level in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.897962 #15]  INFO -- : Replacing (?-mix:#?checkpoint_segments *=.*) with checkpoint_segments = $db_checkpoint_segments in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.898530 #15]  INFO -- : Replacing (?-mix:#?logging_collector *=.*) with logging_collector = $db_logging_collector in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.899047 #15]  INFO -- : Replacing (?-mix:#?log_min_duration_statement *=.*) with log_min_duration_statement = $db_log_min_duration_statement in /etc/postgresql/9.5/main/postgresql.conf
I, [2016-08-09T08:57:58.899576 #15]  INFO -- : Replacing (?-mix:^#local +replication +postgres +peer$) with local replication postgres  peer in /etc/postgresql/9.5/main/pg_hba.conf
I, [2016-08-09T08:57:58.900863 #15]  INFO -- : Replacing (?-mix:^host.*all.*all.*127.*$) with host all all 0.0.0.0/0 md5 in /etc/postgresql/9.5/main/pg_hba.conf
I, [2016-08-09T08:57:58.901288 #15]  INFO -- : > HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/9.5/bin/postmaster -D /etc/postgresql/9.5/main
I, [2016-08-09T08:57:58.902823 #15]  INFO -- : > sleep 5
LOG:  skipping missing configuration file "/shared/postgres_data/postgresql.auto.conf"
2016-08-09 08:57:58 UTC [47-2] FATAL:  data directory "/shared/postgres_data" has group or world access
2016-08-09 08:57:58 UTC [47-3] DETAIL:  Permissions should be u=rwx (0700).
I, [2016-08-09T08:58:03.905141 #15]  INFO -- : 
I, [2016-08-09T08:58:03.906708 #15]  INFO -- : > su postgres -c 'createdb discourse' || true
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2016-08-09T08:58:04.035253 #15]  INFO -- : 
I, [2016-08-09T08:58:04.035768 #15]  INFO -- : > su postgres -c 'psql discourse -c "create user discourse;"' || true
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2016-08-09T08:58:04.163398 #15]  INFO -- : 
I, [2016-08-09T08:58:04.163773 #15]  INFO -- : > su postgres -c 'psql discourse -c "grant all privileges on database discourse to discourse;"' || true
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2016-08-09T08:58:04.257873 #15]  INFO -- : 
I, [2016-08-09T08:58:04.258147 #15]  INFO -- : > su postgres -c 'psql discourse -c "alter schema public owner to discourse;"'
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2016-08-09T08:58:04.351641 #15]  INFO -- : 
I, [2016-08-09T08:58:04.352116 #15]  INFO -- : Terminating async processes


FAILED
--------------------
Pups::ExecError: su postgres -c 'psql discourse -c "alter schema public owner to discourse;"' failed with return #<Process::Status: pid 73 exit 2>
Location of failure: /pups/lib/pups/exec_command.rb:108:in `spawn'
exec failed with the params "su postgres -c 'psql $db_name -c \"alter schema public owner to $db_user;\"'"
1a717333c353cb4f45c0c79c5a508c6136bef3ef7ac17b6db09864ad4ce59f35
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
```

Anyone have an idea how to fix this? I have tried doing everything on a clean install as well, same problems. I'm running Discourse on port `8585` btw.

**Comment by xfalcox** [comment]
Please follow up on meta if it still happening.

**Comment by hvaleanu** [comment]
I have the same kind of error...what was the solution for this? My server was running fine without swap...
but then...

```
cd /pups && git pull && /pups/bin/pups --stdin
Already up-to-date.
I, [2017-04-18T09:37:50.558079 #13]  INFO -- : Loading --stdin
I, [2017-04-18T09:37:50.563428 #13]  INFO -- : > mkdir -p /shared/postgres_run
I, [2017-04-18T09:37:50.566192 #13]  INFO -- :
I, [2017-04-18T09:37:50.566713 #13]  INFO -- : > chown postgres:postgres /shared/postgres_run
I, [2017-04-18T09:37:50.568389 #13]  INFO -- :
I, [2017-04-18T09:37:50.568780 #13]  INFO -- : > chmod 775 /shared/postgres_run
I, [2017-04-18T09:37:50.569973 #13]  INFO -- :
I, [2017-04-18T09:37:50.570292 #13]  INFO -- : > rm -fr /var/run/postgresql
I, [2017-04-18T09:37:50.571553 #13]  INFO -- :
I, [2017-04-18T09:37:50.571868 #13]  INFO -- : > ln -s /shared/postgres_run /var/run/postgresql
I, [2017-04-18T09:37:50.573027 #13]  INFO -- :
I, [2017-04-18T09:37:50.573329 #13]  INFO -- : > socat /dev/null UNIX-CONNECT:/shared/postgres_run/.s.PGSQL.5432 || exit 0 && echo postgres already running stop container ; exit 1
2017/04/18 09:37:50 socat[21] E connect(6, AF=1 "/shared/postgres_run/.s.PGSQL.5432", 36): No such file or directory
I, [2017-04-18T09:37:50.577462 #13]  INFO -- :
I, [2017-04-18T09:37:50.577738 #13]  INFO -- : > rm -fr /shared/postgres_run/.s*
I, [2017-04-18T09:37:50.579469 #13]  INFO -- :
I, [2017-04-18T09:37:50.579732 #13]  INFO -- : > rm -fr /shared/postgres_run/*.pid
I, [2017-04-18T09:37:50.581248 #13]  INFO -- :
I, [2017-04-18T09:37:50.581514 #13]  INFO -- : > mkdir -p /shared/postgres_run/9.5-main.pg_stat_tmp
I, [2017-04-18T09:37:50.582744 #13]  INFO -- :
I, [2017-04-18T09:37:50.583072 #13]  INFO -- : > chown postgres:postgres /shared/postgres_run/9.5-main.pg_stat_tmp
I, [2017-04-18T09:37:50.584369 #13]  INFO -- :
I, [2017-04-18T09:37:50.586947 #13]  INFO -- : File > /etc/service/postgres/run  chmod: +x
I, [2017-04-18T09:37:50.589453 #13]  INFO -- : File > /etc/runit/3.d/99-postgres  chmod: +x
I, [2017-04-18T09:37:50.591778 #13]  INFO -- : File > /root/upgrade_postgres  chmod: +x
I, [2017-04-18T09:37:50.592182 #13]  INFO -- : > chown -R root /var/lib/postgresql/9.5/main
I, [2017-04-18T09:37:50.597974 #13]  INFO -- :
I, [2017-04-18T09:37:50.598349 #13]  INFO -- : > [ ! -e /shared/postgres_data ] && install -d -m 0755 -o postgres -g postgres /shared/postgres_data && sudo -E -u postgres /usr/lib/postgresql/9.5/bin/initdb -D /shared/postgres_data || exit 0
I, [2017-04-18T09:37:50.599840 #13]  INFO -- :
I, [2017-04-18T09:37:50.599937 #13]  INFO -- : > chown -R postgres:postgres /shared/postgres_data
I, [2017-04-18T09:37:50.607311 #13]  INFO -- :
I, [2017-04-18T09:37:50.607762 #13]  INFO -- : > chown -R postgres:postgres /var/run/postgresql
I, [2017-04-18T09:37:50.609445 #13]  INFO -- :
I, [2017-04-18T09:37:50.609862 #13]  INFO -- : > /root/upgrade_postgres
I, [2017-04-18T09:37:50.612924 #13]  INFO -- :
I, [2017-04-18T09:37:50.613222 #13]  INFO -- : > rm /root/upgrade_postgres
I, [2017-04-18T09:37:50.614448 #13]  INFO -- :
I, [2017-04-18T09:37:50.614901 #13]  INFO -- : Replacing data_directory = '/var/lib/postgresql/9.5/main' with data_directory = '/shared/postgres_data' in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.615836 #13]  INFO -- : Replacing (?-mix:#?listen_addresses *=.*) with listen_addresses = '*' in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.616302 #13]  INFO -- : Replacing (?-mix:#?synchronous_commit *=.*) with synchronous_commit = $db_synchronous_commit in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.616727 #13]  INFO -- : Replacing (?-mix:#?shared_buffers *=.*) with shared_buffers = $db_shared_buffers in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.617107 #13]  INFO -- : Replacing (?-mix:#?work_mem *=.*) with work_mem = $db_work_mem in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.617589 #13]  INFO -- : Replacing (?-mix:#?default_text_search_config *=.*) with default_text_search_config = '$db_default_text_search_config' in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.618044 #13]  INFO -- : > install -d -m 0755 -o postgres -g postgres /shared/postgres_backup
I, [2017-04-18T09:37:50.620055 #13]  INFO -- :
I, [2017-04-18T09:37:50.620479 #13]  INFO -- : Replacing (?-mix:#?max_wal_senders *=.*) with max_wal_senders = $db_max_wal_senders in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.620942 #13]  INFO -- : Replacing (?-mix:#?wal_level *=.*) with wal_level = $db_wal_level in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.621331 #13]  INFO -- : Replacing (?-mix:#?checkpoint_segments *=.*) with checkpoint_segments = $db_checkpoint_segments in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.621738 #13]  INFO -- : Replacing (?-mix:#?logging_collector *=.*) with logging_collector = $db_logging_collector in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.622114 #13]  INFO -- : Replacing (?-mix:#?log_min_duration_statement *=.*) with log_min_duration_statement = $db_log_min_duration_statement in /etc/postgresql/9.5/main/postgresql.conf
I, [2017-04-18T09:37:50.622542 #13]  INFO -- : Replacing (?-mix:^#local +replication +postgres +peer$) with local replication postgres  peer in /etc/postgresql/9.5/main/pg_hba.conf
I, [2017-04-18T09:37:50.622880 #13]  INFO -- : Replacing (?-mix:^host.*all.*all.*127.*$) with host all all 0.0.0.0/0 md5 in /etc/postgresql/9.5/main/pg_hba.conf
I, [2017-04-18T09:37:50.623205 #13]  INFO -- : > HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/9.5/bin/postmaster -D /etc/postgresql/9.5/main
I, [2017-04-18T09:37:50.624160 #13]  INFO -- : > sleep 5
2017-04-18 09:37:50 UTC [42-1] FATAL:  data directory "/shared/postgres_data" has group or world access
2017-04-18 09:37:50 UTC [42-2] DETAIL:  Permissions should be u=rwx (0700).
I, [2017-04-18T09:37:55.628964 #13]  INFO -- :
I, [2017-04-18T09:37:55.629678 #13]  INFO -- : > su postgres -c 'createdb discourse' || true
createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2017-04-18T09:37:55.693427 #13]  INFO -- :
I, [2017-04-18T09:37:55.693982 #13]  INFO -- : > su postgres -c 'psql discourse -c "create user discourse;"' || true
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2017-04-18T09:37:55.764180 #13]  INFO -- :
I, [2017-04-18T09:37:55.764816 #13]  INFO -- : > su postgres -c 'psql discourse -c "grant all privileges on database discourse to discourse;"' || true
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2017-04-18T09:37:55.831153 #13]  INFO -- :
I, [2017-04-18T09:37:55.831718 #13]  INFO -- : > su postgres -c 'psql discourse -c "alter schema public owner to discourse;"'
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I, [2017-04-18T09:37:55.900120 #13]  INFO -- :
I, [2017-04-18T09:37:55.900896 #13]  INFO -- : Terminating async processes


FAILED
--------------------
Pups::ExecError: su postgres -c 'psql discourse -c "alter schema public owner to discourse;"' failed with return #<Process::Status: pid 68 exit 2>
Location of failure: /pups/lib/pups/exec_command.rb:108:in `spawn'
exec failed with the params "su postgres -c 'psql $db_name -c \"alter schema public owner to $db_user;\"'"
07126760455e9058c145e69358c01234e7c54a84ba20857afa4efda7111bf471
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
```
